### ISSUE TITLE
Saving after depositing items locks up the game

### ISSUE THREAD

**Issue by PsionicArchon** [janavarro95/Stardew_Valley_Mods#25]
Smapi: 2.2
Stardew Valley: 1.2.33
Save Anywhere: 2.6.1

Steps to reproduce: Deposit items into the chest next to your house and press the save button.

The end of day screen will pop up, you will not be able to click the ok button thus forcing you to close the game. 

No errors appear in the smapi console.

**Comment by ronyjack** [comment]
Pointing some extra I found about this issue: 
1. If saved in SPA, the character will be loaded with clothes on and will be able to run.
2. When the game crashes with the issue above and freezes, even saving, it reseted all completed quests in the day, all itens given to Museum and the item it was left with Clint to upgrade. It also restored all character energy.

**Comment by janavarro95** [comment]
I'll see what I can do with the SPA issue. It makes sense now that I think about it. As for the menu glitch, I JUST finished coding a patch and will upload it shortly once I try to figure out this SPA glitch. The glitch where the day gets reset is due to the fact that the saving would happen AFTER the shipping menu was closed. However because the menu wouldn't close no saving occured. Thanks for letting me know about this one.

**Comment by janavarro95** [comment]
Fixed with update 2.6.2
-You should now be able to exit the shipping calculations menu.
-The spa/swimming issue should be fixed and working now.
